apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-ha
  namespace: prometheus-ha
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus-ha
  namespace: prometheus-ha
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus-ha
subjects:
  - kind: ServiceAccount
    name: prometheus-ha
    namespace: prometheus-ha
roleRef:
  kind: ClusterRole
  name: prometheus-ha
  apiGroup: rbac.authorization.k8s.io
---